In [6]:
import onnx
from onnx_tf.backend import prepare

onnx_model = onnx.load("network2.onnx")  # load onnx model
tf_rep = prepare(onnx_model)  # prepare tf representation
tf_rep.export_graph("output_path")  # export the model

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 4, expecting 3
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 4, expecting 3
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
INFO:tensorflow:Assets written to: output_path\assets


In [44]:
import onnx
from onnx_tf.backend import prepare
import numpy as np
import cv2
from PIL import Image
# model = onnx.load('network2.onnx') # Load the ONNX file
# tf_model = prepare(model) # Import the ONNX model to Tensorflow
from keras.models import load_model
# model =load_model('test.h5', compile=False)
# img = Image.open('images/palec3.jpg').resize((224, 224))
# img = np.asarray(img, dtype=np.float32)[np.newaxis, np.newaxis, :, :]
# img = img.transpose(0,1,4,2,3)
# img = img.reshape(224,224) # Transform to Input Tensor
def prepare(file):
    IMG_SIZE = 224
    img_array = cv2.imread(file)
    new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE),3)
    return new_array.reshape(IMG_SIZE, IMG_SIZE)

def load_image_into_numpy_array(image):
    (im_width, im_height) = image.size
    if image.getdata().mode == "RGBA":
        image = image.convert('RGB')
    np_array = np.array(image.getdata())
    reshaped = np_array.reshape((im_height, im_width, 3))
    return reshaped.astype(np.uint8)

img = Image.open('images/paszport2.jpg').resize((224, 224))
# print(Image.open('images/paszport2.jpg').resize((224, 224)))
x = load_image_into_numpy_array(img)
print(x.shape)
x.reshape((224, 224, 3))
print(x)
# image = prepare("data/paszport2.jpg").astype(np.float32)

prediction = model.predict(x)
print(prediction)
prediction = list(prediction[0])
print(CATEGORIES[prediction.index(max(prediction))])
print(max(prediction)*100)
# Y = tf_model.run(img)[0][0] #Inference

(224, 224, 3)
[[[150 147 131]
  [154 153 135]
  [152 150 134]
  ...
  [148 149 131]
  [140 141 122]
  [227 227 223]]

 [[174 172 158]
  [170 169 154]
  [169 169 155]
  ...
  [155 156 140]
  [148 149 132]
  [229 229 225]]

 [[199 197 184]
  [192 190 177]
  [191 191 178]
  ...
  [165 166 152]
  [160 160 145]
  [231 231 228]]

 ...

 [[232 228 218]
  [227 223 214]
  [226 222 211]
  ...
  [237 233 221]
  [236 232 221]
  [250 249 247]]

 [[229 225 217]
  [224 219 212]
  [226 222 210]
  ...
  [234 231 225]
  [232 229 223]
  [250 249 247]]

 [[229 224 218]
  [224 219 212]
  [226 223 209]
  ...
  [229 226 221]
  [228 224 221]
  [249 248 247]]]


ValueError: Input 0 of layer zero_padding2d is incompatible with the layer: expected ndim=4, found ndim=3. Full shape received: [32, 224, 3]

In [46]:

# Load the ONNX model
model = onnx.load("x.onnx")

# Check that the IR is well formed
onnx.checker.check_model(model)

# Print a human readable representation of the graph
onnx.helper.printable_graph(model.graph)

'graph torch-jit-export (\n  %input[FLOAT, batch_sizex3x7x7]\n) initializers (\n  %bn1.bias[FLOAT, 64]\n  %bn1.running_mean[FLOAT, 64]\n  %bn1.running_var[FLOAT, 64]\n  %bn1.weight[FLOAT, 64]\n  %conv1.weight[FLOAT, 64x3x7x7]\n  %fc.0.bias[FLOAT, 128]\n  %fc.0.weight[FLOAT, 128x2048]\n  %fc.2.bias[FLOAT, 8]\n  %fc.2.weight[FLOAT, 8x128]\n  %layer1.0.bn1.bias[FLOAT, 64]\n  %layer1.0.bn1.running_mean[FLOAT, 64]\n  %layer1.0.bn1.running_var[FLOAT, 64]\n  %layer1.0.bn1.weight[FLOAT, 64]\n  %layer1.0.bn2.bias[FLOAT, 64]\n  %layer1.0.bn2.running_mean[FLOAT, 64]\n  %layer1.0.bn2.running_var[FLOAT, 64]\n  %layer1.0.bn2.weight[FLOAT, 64]\n  %layer1.0.bn3.bias[FLOAT, 256]\n  %layer1.0.bn3.running_mean[FLOAT, 256]\n  %layer1.0.bn3.running_var[FLOAT, 256]\n  %layer1.0.bn3.weight[FLOAT, 256]\n  %layer1.0.conv1.weight[FLOAT, 64x64x1x1]\n  %layer1.0.conv2.weight[FLOAT, 64x64x3x3]\n  %layer1.0.conv3.weight[FLOAT, 256x64x1x1]\n  %layer1.0.downsample.0.weight[FLOAT, 256x64x1x1]\n  %layer1.0.downsample.1

In [49]:
import onnxruntime as ort

ort_session = ort.InferenceSession('x.onnx')

outputs = ort_session.run(None, {'input': np.random.randn(10, 3, 7, 7).astype(np.float32)})

print(outputs[0])

[[ -0.72334975   2.9887626    5.689066    -2.0996385   -7.2423058
   -8.168665    -4.340163     1.9838402 ]
 [  2.0510168    4.04455      2.4237616   -1.151059    -2.655688
   -8.0933      -6.52764      0.75642246]
 [  6.5040064    2.8785172    7.4513907   -7.912492   -14.4503355
  -10.534207     1.9296216    1.364879  ]
 [  0.51105064   7.255149     5.513964    -9.846073   -16.241962
   -7.9701858   -2.4136124    7.9025865 ]
 [  1.5310289   -0.8831662    3.8414583    0.08444295   0.4156746
   -8.478446    -7.9875975    1.2635792 ]
 [  4.270699     7.1135592    6.0154734   -7.4166684  -16.210575
   -9.560787    -0.29917705   3.3115702 ]
 [  0.19368464   7.776965     2.7018619   -6.2014623  -13.324469
   -5.2030673   -3.1886861    6.330359  ]
 [  4.6642795    4.7844605    4.1729684   -6.434046   -13.331917
   -7.0348406    1.5526292    2.3930278 ]
 [  6.1770916    7.643621     3.2877774   -5.034087   -11.339336
  -10.5702095   -6.230276     3.0284247 ]
 [  5.0252123    1.762348     4.45